name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Save timestamp
      run: |
        TIMESTAMP=$(date +%s)
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}


    - name: Build and Push Docker image to Docker Hub
      run:  |
            docker build . --file ./docker/wvp/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/docker-wvp:$TIMESTAMP --tag ${{ secrets.DOCKER_USERNAME }}/docker-wvp:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/docker-wvp:$TIMESTAMP
            docker push ${{ secrets.DOCKER_USERNAME }}/docker-wvp:latest
    
